/**
 * SUBUNDERGRUND ELECTRONIC - Factory Instrument Presets
 * 8-Filter Bank Synthesizer Architecture
 * 
 * Each instrument is purely synthesized from a base frequency (f0)
 * passing through 8 configurable filter stages (tracking, peaking, formant, etc.)
 */

export const INSTRUMENT_PRESETS = [
  {
    id: 'sub-bass',
    name: 'Sub Underground Bass',
    category: 'Bass',
    description: 'Глибокий, щільний суб-бас із резонансним піком на суб-гармоніках',
    icon: 'waveform_path',
    color: 'orange',
    waveform: 'sawtooth',
    envelope: { attack: 0.005, decay: 0.25, sustain: 0.7, release: 0.15 },
    filters: [
      { id: 1, name: 'Sub Fundamental', type: 'lowpass', tracking: true, freqMult: 1.0, freqHz: 80, q: 3.0, gain: 0, bypass: false },
      { id: 2, name: '2nd Harmonic Peak', type: 'peaking', tracking: true, freqMult: 2.0, freqHz: 160, q: 4.0, gain: 6, bypass: false },
      { id: 3, name: 'Warmth Body', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 120, q: 2.0, gain: 4, bypass: false },
      { id: 4, name: 'Mud Cut', type: 'notch', tracking: false, freqMult: 1.0, freqHz: 350, q: 2.5, gain: -8, bypass: false },
      { id: 5, name: 'Lowpass Slope 1', type: 'lowpass', tracking: true, freqMult: 3.5, freqHz: 600, q: 1.2, gain: 0, bypass: false },
      { id: 6, name: 'Lowpass Slope 2', type: 'lowpass', tracking: false, freqMult: 1.0, freqHz: 850, q: 1.0, gain: 0, bypass: false },
      { id: 7, name: 'High Shelf Tame', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 2500, q: 1.0, gain: -14, bypass: false },
      { id: 8, name: 'Sub Saturation Air', type: 'allpass', tracking: true, freqMult: 1.0, freqHz: 100, q: 1.0, gain: 0, bypass: true },
    ],
  },
  {
    id: 'acid-303',
    name: 'Acid 303 Resonator',
    category: 'Bass/Lead',
    description: 'Агресивний резонансний кислотний бас із гострим фільтром та скрекотом',
    icon: 'bolt',
    color: 'green',
    waveform: 'sawtooth',
    envelope: { attack: 0.002, decay: 0.35, sustain: 0.15, release: 0.1 },
    filters: [
      { id: 1, name: 'Highpass Rumble Clean', type: 'highpass', tracking: false, freqMult: 1.0, freqHz: 35, q: 0.8, gain: 0, bypass: false },
      { id: 2, name: 'Acid Reso Peak 1', type: 'bandpass', tracking: true, freqMult: 2.5, freqHz: 1200, q: 12.0, gain: 0, bypass: false },
      { id: 3, name: 'Screaming Q Stage', type: 'peaking', tracking: true, freqMult: 4.0, freqHz: 2400, q: 9.0, gain: 9, bypass: false },
      { id: 4, name: 'Acid Lowpass 18dB', type: 'lowpass', tracking: true, freqMult: 5.0, freqHz: 1800, q: 6.5, gain: 0, bypass: false },
      { id: 5, name: 'Formant Bite', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 1600, q: 4.0, gain: 6, bypass: false },
      { id: 6, name: 'Notch Whistle', type: 'notch', tracking: true, freqMult: 6.0, freqHz: 3600, q: 3.0, gain: 0, bypass: false },
      { id: 7, name: 'Aggressive Highshelf', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 4500, q: 1.0, gain: -6, bypass: false },
      { id: 8, name: 'Allpass Phase Smear', type: 'allpass', tracking: true, freqMult: 2.0, freqHz: 800, q: 2.0, gain: 0, bypass: false },
    ],
  },
  {
    id: 'electric-tine',
    name: 'Electric Tine Piano',
    category: 'Keys',
    description: 'Дзвінкий тембр електромеханічного піаніно (Rhodes/FM) з металевими обертонами',
    icon: 'tuningfork',
    color: 'blue',
    waveform: 'triangle',
    envelope: { attack: 0.003, decay: 0.8, sustain: 0.25, release: 0.4 },
    filters: [
      { id: 1, name: 'Body Fundamental', type: 'peaking', tracking: true, freqMult: 1.0, freqHz: 260, q: 2.0, gain: 5, bypass: false },
      { id: 2, name: 'Octave Harmonic', type: 'peaking', tracking: true, freqMult: 2.0, freqHz: 520, q: 3.5, gain: 4, bypass: false },
      { id: 3, name: 'Bell Tine 1 (Inharmonic)', type: 'peaking', tracking: true, freqMult: 2.76, freqHz: 720, q: 8.0, gain: 7, bypass: false },
      { id: 4, name: 'Bell Tine 2 (Chime)', type: 'peaking', tracking: true, freqMult: 5.4, freqHz: 1400, q: 11.0, gain: 8, bypass: false },
      { id: 5, name: 'Bark Mid Resonance', type: 'bandpass', tracking: true, freqMult: 3.0, freqHz: 900, q: 2.5, gain: 0, bypass: false },
      { id: 6, name: 'Tine Click Highs', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 3800, q: 4.0, gain: 6, bypass: false },
      { id: 7, name: 'Warm Lowpass', type: 'lowpass', tracking: false, freqMult: 1.0, freqHz: 5500, q: 0.7, gain: 0, bypass: false },
      { id: 8, name: 'Chamber Phase', type: 'allpass', tracking: false, freqMult: 1.0, freqHz: 1100, q: 1.5, gain: 0, bypass: false },
    ],
  },
  {
    id: 'cyber-lead',
    name: 'Cyberpunk Saw Lead',
    category: 'Lead',
    description: 'Потужний, прорізний синт-лід для соло та футуристичних партій',
    icon: 'sparkles',
    color: 'pink',
    waveform: 'sawtooth',
    envelope: { attack: 0.015, decay: 0.4, sustain: 0.75, release: 0.25 },
    filters: [
      { id: 1, name: 'Presence Lowpass', type: 'lowpass', tracking: true, freqMult: 8.0, freqHz: 3500, q: 4.0, gain: 0, bypass: false },
      { id: 2, name: 'Harmonic Edge 1', type: 'peaking', tracking: true, freqMult: 3.0, freqHz: 1200, q: 3.0, gain: 5, bypass: false },
      { id: 3, name: 'Harmonic Edge 2', type: 'peaking', tracking: true, freqMult: 5.0, freqHz: 2000, q: 4.0, gain: 4, bypass: false },
      { id: 4, name: 'Formant Bite', type: 'bandpass', tracking: false, freqMult: 1.0, freqHz: 2800, q: 3.5, gain: 0, bypass: false },
      { id: 5, name: 'Air Highshelf', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 6000, q: 1.0, gain: 5, bypass: false },
      { id: 6, name: 'Mid Body Notch', type: 'notch', tracking: false, freqMult: 1.0, freqHz: 800, q: 2.0, gain: 0, bypass: true },
      { id: 7, name: 'Lead Low Shelf Fat', type: 'lowshelf', tracking: false, freqMult: 1.0, freqHz: 200, q: 1.0, gain: 3, bypass: false },
      { id: 8, name: 'Lead Sizzle Limiter', type: 'lowpass', tracking: false, freqMult: 1.0, freqHz: 14000, q: 0.7, gain: 0, bypass: false },
    ],
  },
  {
    id: 'vocal-formant',
    name: 'Vocal Formant Choir',
    category: 'Formant',
    description: 'Органічний вокальний тембр голосу/хору на базі акустичних формант F1, F2, F3',
    icon: 'person_2',
    color: 'purple',
    waveform: 'sawtooth',
    envelope: { attack: 0.06, decay: 0.5, sustain: 0.6, release: 0.4 },
    filters: [
      { id: 1, name: 'Formant F1 (Vowel A)', type: 'bandpass', tracking: false, freqMult: 1.0, freqHz: 800, q: 6.0, gain: 0, bypass: false },
      { id: 2, name: 'Formant F2 (Vowel O)', type: 'bandpass', tracking: false, freqMult: 1.0, freqHz: 1200, q: 7.0, gain: 0, bypass: false },
      { id: 3, name: 'Formant F3 (Singers Formant)', type: 'bandpass', tracking: false, freqMult: 1.0, freqHz: 2800, q: 8.0, gain: 0, bypass: false },
      { id: 4, name: 'Chest Resonance', type: 'peaking', tracking: true, freqMult: 1.0, freqHz: 200, q: 3.0, gain: 6, bypass: false },
      { id: 5, name: 'Nasal Notch', type: 'notch', tracking: false, freqMult: 1.0, freqHz: 1800, q: 3.5, gain: 0, bypass: false },
      { id: 6, name: 'Vocal Presence Peak', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 3400, q: 4.0, gain: 4, bypass: false },
      { id: 7, name: 'Low Rumble Cut', type: 'highpass', tracking: false, freqMult: 1.0, freqHz: 100, q: 0.7, gain: 0, bypass: false },
      { id: 8, name: 'Breath Air Shelf', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 7500, q: 1.0, gain: -5, bypass: false },
    ],
  },
  {
    id: 'liquid-pluck',
    name: 'Liquid Reso Pluck',
    category: 'Pluck',
    description: 'Пружний щипковий звук із коротким дзвінким загасанням для арпеджіо',
    icon: 'music_note',
    color: 'teal',
    waveform: 'square',
    envelope: { attack: 0.001, decay: 0.22, sustain: 0.05, release: 0.18 },
    filters: [
      { id: 1, name: 'Pluck Attack Transient', type: 'bandpass', tracking: true, freqMult: 4.0, freqHz: 1800, q: 9.0, gain: 0, bypass: false },
      { id: 2, name: 'Harmonic Body', type: 'peaking', tracking: true, freqMult: 2.0, freqHz: 800, q: 4.0, gain: 6, bypass: false },
      { id: 3, name: 'Main Damp Lowpass', type: 'lowpass', tracking: true, freqMult: 3.0, freqHz: 1200, q: 3.0, gain: 0, bypass: false },
      { id: 4, name: 'High Sparkle Peak', type: 'peaking', tracking: true, freqMult: 6.0, freqHz: 3200, q: 7.0, gain: 5, bypass: false },
      { id: 5, name: 'Sub Anchor', type: 'lowshelf', tracking: true, freqMult: 1.0, freqHz: 150, q: 1.0, gain: 3, bypass: false },
      { id: 6, name: 'Mids Anti-Hollow', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 650, q: 2.0, gain: -3, bypass: false },
      { id: 7, name: 'Tail Damping Shelf', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 4000, q: 1.0, gain: -10, bypass: false },
      { id: 8, name: 'Phase Resonator', type: 'allpass', tracking: true, freqMult: 1.5, freqHz: 500, q: 2.5, gain: 0, bypass: false },
    ],
  },
  {
    id: 'metallic-bell',
    name: 'Metallic Bell / Anvil',
    category: 'Percussion',
    description: 'Металевий дзвін та гонг на базі негармонічних добротних пікових фільтрів',
    icon: 'bell',
    color: 'yellow',
    waveform: 'square',
    envelope: { attack: 0.002, decay: 1.2, sustain: 0.08, release: 0.6 },
    filters: [
      { id: 1, name: 'Strike Transient', type: 'highpass', tracking: false, freqMult: 1.0, freqHz: 120, q: 1.5, gain: 0, bypass: false },
      { id: 2, name: 'Fundamental Strike', type: 'peaking', tracking: true, freqMult: 1.0, freqHz: 440, q: 14.0, gain: 10, bypass: false },
      { id: 3, name: 'Inharmonic Mode 1 (1.41x)', type: 'peaking', tracking: true, freqMult: 1.414, freqHz: 622, q: 16.0, gain: 9, bypass: false },
      { id: 4, name: 'Inharmonic Mode 2 (2.36x)', type: 'peaking', tracking: true, freqMult: 2.36, freqHz: 1038, q: 18.0, gain: 8, bypass: false },
      { id: 5, name: 'Inharmonic Mode 3 (3.82x)', type: 'peaking', tracking: true, freqMult: 3.82, freqHz: 1680, q: 15.0, gain: 7, bypass: false },
      { id: 6, name: 'Anvil Clang Band', type: 'bandpass', tracking: true, freqMult: 5.25, freqHz: 2310, q: 12.0, gain: 0, bypass: false },
      { id: 7, name: 'Metallic Shimmer High', type: 'peaking', tracking: false, freqMult: 1.0, freqHz: 5200, q: 10.0, gain: 6, bypass: false },
      { id: 8, name: 'High Damp Lowpass', type: 'lowpass', tracking: false, freqMult: 1.0, freqHz: 9000, q: 0.8, gain: 0, bypass: false },
    ],
  },
  {
    id: 'ambient-pad',
    name: 'Atmospheric Ethereal Pad',
    category: 'Pad',
    description: 'Мʼякий ембієнт-пед із плавним розгортанням та фазовою глибиною',
    icon: 'cloud',
    color: 'lightblue',
    waveform: 'sawtooth',
    envelope: { attack: 0.45, decay: 1.2, sustain: 0.85, release: 1.1 },
    filters: [
      { id: 1, name: 'Sub Gentle Floor', type: 'lowshelf', tracking: false, freqMult: 1.0, freqHz: 140, q: 0.7, gain: 4, bypass: false },
      { id: 2, name: 'Warm Breath Cutoff', type: 'lowpass', tracking: true, freqMult: 4.5, freqHz: 1400, q: 2.2, gain: 0, bypass: false },
      { id: 3, name: 'Mid Air Reso 1', type: 'bandpass', tracking: true, freqMult: 2.0, freqHz: 700, q: 3.0, gain: 0, bypass: false },
      { id: 4, name: 'Mid Air Reso 2', type: 'bandpass', tracking: true, freqMult: 3.5, freqHz: 1250, q: 4.0, gain: 0, bypass: false },
      { id: 5, name: 'Ethereal Notch 1', type: 'notch', tracking: false, freqMult: 1.0, freqHz: 1900, q: 2.0, gain: 0, bypass: false },
      { id: 6, name: 'Silky High Shelf', type: 'highshelf', tracking: false, freqMult: 1.0, freqHz: 3500, q: 0.8, gain: -4, bypass: false },
      { id: 7, name: 'Phase Diffusion 1', type: 'allpass', tracking: false, freqMult: 1.0, freqHz: 650, q: 3.0, gain: 0, bypass: false },
      { id: 8, name: 'Phase Diffusion 2', type: 'allpass', tracking: false, freqMult: 1.0, freqHz: 1800, q: 2.5, gain: 0, bypass: false },
    ],
  },
];

export default INSTRUMENT_PRESETS;
